[package]
name = "pipec-cache"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
bincode = { version = "2.0.1", features = ["derive"] }
serde = "1.0.228"
pipec-globals = { version = "0.1.0", path = "../pipec-globals" }
