[workspace]
resolver = "3"
members = ["pipecc","pipec-globals","pipec-errors","pipec-cache","pipec-ast","pipec-args", "pipec-mir", "pipec-tests", "pipec-semantic-analysis", "pipec-prelude"]

[profile.release]
debug = true
