[workspace]
resolver = "3"
members = ["pipecc","pipec-globals","pipec-errors","pipec-ast","pipec-args", "pipec-mir", "pipec-tests", "pipec-semantic-analysis", "pipec-prelude", "pipec-arena", "pipec-span"]

[profile.release]
debug = true
