name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: blacksmith-4vcpu-ubuntu-2404-arm
    

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory : ./compiler
      run: rustup update && cargo build --verbose
    - name: Run tests
      working-directory : ./compiler
      run: cargo test --verbose
    - name: Do linting
      working-directory : ./compiler
      run: cargo clippy -- -D warnings
